spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://129.211.81.88:3306/battalion?characterEncoding=utf-8&&serverTimezone=GMT%2B8
    username: root
    password: PengZiHao1999.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
  thymeleaf:
    cache: false
logging:
  level:
    root: info
    com.lrm: debug
  file: log/blog-dev.log
server:
  port: 8080


